select O_ORDERKEY AS ORDER_ID,
O_CUSTKEY AS CUST_ID,
O_ORDERSTATUS AS ORDER_STATUS,
O_ORDERDATE AS ORDER_DATE,
O_TOTALPRICE AS ORDER_AMT,
md5(O_ORDERSTATUS||O_ORDERDATE||O_TOTALPRICE) AS HASH_VAL,
CURRENT_TIMESTAMP AS LOADDATETIME
FROM  {{ source('CRM', 'orders') }}
ORDER BY CUST_ID --