version: 2

sources:
  - name: CRM
    database: RAW
    schema: LANDING
    tables:
      - name: orders
      - name: customer
      - name: nation
      - name: customer_subscription

  - name: ABC
    database: AUDIT
    schema: EXECUTION_LOGS
    tables:
      - name: JOB_RUN_HISTORY