version: 2

sources:
  - name: CRM
    database: "{{env_var('DBT_RAW_DB')}}"
    schema: "{{env_var('DBT_LANDING_SCHEMA')}}"
    tables:
      - name: orders
      - name: customer
      - name: nation
      - name: customer_subscription
      - name: country_state

  - name: ABC
    database: "{{env_var('DBT_AUDIT_DB')}}"
    schema: "{{env_var('DBT_LOGS_SCHEMA')}}"
    tables:
      - name: JOB_RUN_HISTORY